export const CHANGE_MODE = "CHANGE_MODE";
export const CHANGE_NOTIFICATIONS = "CHANGE_NOTIFICATIONS";
export const CHANGE_FORM_NAME = "CHANGE_FORM_NAME";
export const CHANGE_FORM_TYPE = "CHANGE_FORM_TYPE";
export const CHANGE_FORM_ICON = "CHANGE_FORM_ICON";

export const ADD_TO_LIST = "ADD_TO_LIST";
export const EDIT_LIST = "EDIT_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const RESET_FORM = "RESET_FORM";
export const CHANGE_ACTUAL_LIST = "CHANGE_ACTUAL_LIST";
export const CHANGE_NEW_EXERCISE_NAME = "CHANGE_NEW_EXERCISE_NAME";
export const ADD_NEW_EXERCISE = "ADD_NEW_EXERCISE";
export const RESET_NEW_EXERCISE_INPUT = "RESET_NEW_EXERCISE_INPUT";
export const EDIT_NOTE = "EDIT_NOTE";
export const DELETE_EXERCISE = "DELETE_EXERCISE";
